; Ajustes de ambiente para desenvolvimento local (docker).

upload_max_filesize = 20M
post_max_size = 20M
memory_limit = 256M
max_execution_time = 60

display_errors = On
display_startup_errors = On
error_reporting = E_ALL

date.timezone = America/Sao_Paulo

opcache.enable = 1
opcache.validate_timestamps = 1
opcache.revalidate_freq = 0
