INSERT INTO posts (title, slug, excerpt, content, author_name, featured_image, published_at) VALUES
('Primeiros passos com PHP puro', 'primeiros-passos-com-php-puro', 'Uma introducao pratica para organizar um projeto PHP sem framework.', 'Criar um projeto em PHP puro ajuda a entender o ciclo completo da requisicao.\n\nA separacao em MVC deixa cada responsabilidade em seu lugar e facilita manutencao.', 'Paulo Silva', '/assets/images/blog-feature.svg', '2026-04-20 09:00:00'),
('MVC simples para blogs', 'mvc-simples-para-blogs', 'Como dividir controllers, models e views em uma aplicacao pequena.', 'Controllers devem coordenar entrada e saida, sem concentrar regras de negocio.\n\nModels, services e repositories podem crescer conforme a necessidade real do projeto.', 'Marina Costa', '/assets/images/blog-feature.svg', '2026-04-19 09:00:00'),
('Roteamento amigavel em PHP', 'roteamento-amigavel-em-php', 'URLs legiveis tornam o blog melhor para pessoas e buscadores.', 'Um front controller centraliza as requisicoes e simplifica o roteamento.\n\nSlugs claros ajudam SEO e deixam os links mais faceis de compartilhar.', 'Equipe Editorial', '/assets/images/blog-feature.svg', '2026-04-18 09:00:00'),
('PDO e consultas seguras', 'pdo-e-consultas-seguras', 'Prepared statements reduzem riscos ao consultar o MySQL.', 'PDO oferece uma interface consistente para acesso ao banco de dados.\n\nConsultas parametrizadas devem ser o padrao para dados recebidos do usuario.', 'Rafael Lima', '/assets/images/blog-feature.svg', '2026-04-17 09:00:00'),
('Organizando views minimalistas', 'organizando-views-minimalistas', 'Layouts simples melhoram leitura e reduzem distracoes.', 'Um blog precisa priorizar titulo, data, autor e conteudo.\n\nBootstrap 5 pode resolver a base visual sem excesso de codigo customizado.', 'Ana Martins', '/assets/images/blog-feature.svg', '2026-04-16 09:00:00'),
('SEO tecnico para posts', 'seo-tecnico-para-posts', 'Metadados e HTML semantico ajudam os posts a serem encontrados.', 'Cada pagina deve ter title, description e um unico h1 claro.\n\nImagens com alt e slugs descritivos reforcam a qualidade da pagina.', 'Equipe Editorial', '/assets/images/blog-feature.svg', '2026-04-15 09:00:00'),
('Paginacao no backend', 'paginacao-no-backend', 'Carregar poucos posts por pagina deixa a listagem mais rapida.', 'A paginacao deve calcular limite, offset e total de paginas no servidor.\n\nIsso evita respostas grandes e mantem a navegacao previsivel.', 'Paulo Silva', '/assets/images/blog-feature.svg', '2026-04-14 09:00:00'),
('Separando acesso a dados', 'separando-acesso-a-dados', 'Repositories deixam consultas SQL fora dos controllers.', 'A separacao de responsabilidades evita que controllers conhecam detalhes demais do banco.\n\nRepositories tambem facilitam testar consultas e reaproveitar criterios.', 'Marina Costa', '/assets/images/blog-feature.svg', '2026-04-13 09:00:00'),
('Ambiente com arquivo env', 'ambiente-com-arquivo-env', 'Configuracoes sensiveis devem ficar fora do codigo versionado.', 'O arquivo .env guarda credenciais e ajustes locais.\n\nO repositorio deve manter apenas um .env.example com valores de referencia.', 'Rafael Lima', '/assets/images/blog-feature.svg', '2026-04-12 09:00:00'),
('Migrations com SQL puro', 'migrations-com-sql-puro', 'Scripts SQL versionados ajudam a controlar mudancas no banco.', 'Uma tabela de migrations registra o que ja foi executado.\n\nEsse controle evita reaplicar scripts e torna o ambiente reproduzivel.', 'Ana Martins', '/assets/images/blog-feature.svg', '2026-04-11 09:00:00'),
('Componentes Bootstrap no blog', 'componentes-bootstrap-no-blog', 'Bootstrap acelera a criacao de interfaces consistentes.', 'Grades, botoes e espacamentos padronizados resolvem boa parte do layout.\n\nO visual final ainda deve ser simples e focado no conteudo.', 'Equipe Editorial', '/assets/images/blog-feature.svg', '2026-04-10 09:00:00'),
('Quando usar jQuery', 'quando-usar-jquery', 'jQuery deve entrar apenas quando simplificar interacoes.', 'Nem toda pagina precisa de JavaScript.\n\nQuando houver comportamento dinamico, escolha a solucao mais clara para manter.', 'Paulo Silva', '/assets/images/blog-feature.svg', '2026-04-09 09:00:00'),
('Namespaces no PHP', 'namespaces-no-php', 'Namespaces deixam as classes organizadas e evitam conflitos.', 'A estrutura App\\Controllers e App\\Repositories comunica a responsabilidade de cada classe.\n\nUm autoloader simples pode carregar tudo sem Composer.', 'Marina Costa', '/assets/images/blog-feature.svg', '2026-04-08 09:00:00'),
('Controllers enxutos', 'controllers-enxutos', 'Controllers devem delegar consultas e regras complexas.', 'A action deve receber a requisicao, chamar dependencias e escolher a resposta.\n\nEsse limite reduz acoplamento e facilita evoluir o projeto.', 'Rafael Lima', '/assets/images/blog-feature.svg', '2026-04-07 09:00:00'),
('Listagens eficientes', 'listagens-eficientes', 'Consultas com LIMIT e OFFSET ajudam no desempenho inicial.', 'Para blogs pequenos, paginacao classica resolve bem.\n\nProjetos maiores podem evoluir para estrategias baseadas em cursor.', 'Ana Martins', '/assets/images/blog-feature.svg', '2026-04-06 09:00:00'),
('Detalhe do post', 'detalhe-do-post', 'A leitura individual deve destacar o conteudo principal.', 'Uma imagem destacada cria contexto visual sem competir com o texto.\n\nLinks para posts anterior e proximo aumentam a descoberta de conteudo.', 'Equipe Editorial', '/assets/images/blog-feature.svg', '2026-04-05 09:00:00'),
('Datas de publicacao', 'datas-de-publicacao', 'Datas claras ajudam o leitor a entender a atualidade do conteudo.', 'Exibir data e autor melhora transparencia editorial.\n\nEssas informacoes tambem ajudam buscadores a interpretar a pagina.', 'Paulo Silva', '/assets/images/blog-feature.svg', '2026-04-04 09:00:00'),
('Slugs legiveis', 'slugs-legiveis', 'Slugs curtos e descritivos melhoram compartilhamento e SEO.', 'Evite IDs expostos quando o titulo pode formar uma URL clara.\n\nTambem e importante garantir unicidade no banco.', 'Marina Costa', '/assets/images/blog-feature.svg', '2026-04-03 09:00:00'),
('Seguranca em views', 'seguranca-em-views', 'Escapar saidas HTML evita problemas comuns de seguranca.', 'Todo dado vindo do banco deve ser tratado antes de aparecer no HTML.\n\nFuncoes como htmlspecialchars devem ser aplicadas nas views.', 'Rafael Lima', '/assets/images/blog-feature.svg', '2026-04-02 09:00:00'),
('Base pronta para evoluir', 'base-pronta-para-evoluir', 'Uma estrutura pequena pode crescer sem perder clareza.', 'Comece com MVC simples e adicione camadas apenas quando houver necessidade.\n\nEssa disciplina mantem o projeto facil de entender.', 'Ana Martins', '/assets/images/blog-feature.svg', '2026-04-01 09:00:00')
ON DUPLICATE KEY UPDATE
    title = VALUES(title),
    excerpt = VALUES(excerpt),
    content = VALUES(content),
    author_name = VALUES(author_name),
    featured_image = VALUES(featured_image),
    published_at = VALUES(published_at);

